const characters = [
  {
    identifier: "babyYoda",
    name: "Baby Yoda",
    gif: "assets/baby_yoda_stats.gif",
    age: "?????",
    home: "?????",
    url: "assets/baby_yoda_icon_4.png",
    left: "assets/baby_yoda_facing_left.png",
    right: "assets/baby_yoda_facing_right.png",
    select: "SELECT",
  },
  {
    identifier: "babySpongeBob",
    name: "Baby SpongeBob",
    gif: "assets/baby_spongebob_stats.gif",
    age: "Two Years Old",
    home: "Bikini Bottom",
    url: "assets/baby_spongebob.png",
    left: "assets/baby_spongebob_facing_left.png",
    right: "assets/baby_spongebob_facing_right.png",
    select: "SELECT",
  },
  {
    identifier: "babyGroot",
    name: "Baby Groot",
    gif: "assets/baby_groot_stats.gif",
    age: "Two Years Old",
    home: "Planet X",
    url: "assets/baby_groot_new_icon.png",
    left: "assets/baby_groot_facing_left.png",
    right: "assets/baby_groot_facing_right.png",
    select: "SELECT",
  },
];

const resultsImages = [
    "assets/baby_groot_you_win.gif",
    "assets/baby_spongebob_you_win.gif",
    "assets/baby_yoda_you_win.gif",
    "assets/baby_yoda_sipping_gif.gif",
    "assets/baby_yoda_sleeping.gif",
    "assets/baby_yoda_waving.gif",
    "assets/baby_spongebob_plankton.gif",
    "assets/baby_groot_dancing.gif",
    "assets/baby_groot_angry.gif",
    "assets/baby_groot_cheer.gif",
  ];

  const backgroundImages = [
    "nYuVFMI.gif",
    "bg1.gif",
    "bg2.gif",
    "bg3.gif",
    "bg4.gif",
    "bg5.gif",
    "bg6.gif",
    "bg7.gif",
    "bg8.gif",
    "bg9.gif",
    "bg10.gif",
    "bg11.gif",
    "bg12.gif",
    "bg13.gif",
    "bg14.gif",
    "bg15.gif",
    "bg16.gif",
    "bg17.gif",
    "bg18.gif",
    "bg19.gif",
    "bg20.gif",
  ];